Map controls in header are responsive for small screens
getappmap/appmap-js pull request #1049
Opened 2023-02-17 21:39 UTC by typaulhus

Closes #1048 
![tab-control-small-screen](https://user-images.githubusercontent.com/123787/219798778-bf7d18ac-fc62-481f-b5df-9ff98ef10711.gif)

2023-02-20 22:18 UTC, Daniel-Warner-X commented
@typaulhus I am still seeing issues in storybook... am I looking in the right place?
<img width="821" alt="image" src="https://user-images.githubusercontent.com/1229326/220206364-2dbf2295-5f61-4585-9b95-7ca44e39b550.png">
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/1229326/220206420-d689cdfd-0e0b-4ad6-a76b-77a4124b8e53.png">

2023-02-21 15:56 UTC, typaulhus commented
I made some updates to the responsive tabs. Can you take a look @Daniel-Warner-X & @ahtrotta ? 

I'd like to get rid of the big purple buttons for the Share & Export controls, they're different than all the others without a clear reason why. Could we just use icons for those like the others?

![responsive-tabs](https://user-images.githubusercontent.com/123787/220394887-34d13b73-ff35-4039-9985-9deed4be4b85.gif)

2023-02-22 14:02 UTC, ahtrotta requested changes

2023-02-22 14:02 UTC, ahtrotta commented on packages/components/src/components/Tabs.vue
> -    position: absolute;
@ty we can't change this property because it fixes a bug. See [here](https://github.com/getappmap/appmap-js/issues/1015).

2023-02-22 17:58 UTC, merged