Stats command relative path support
getappmap/appmap-js pull request #1366
Opened 2023-09-09 14:13 UTC by moxw

Fixes #1200 

refactor(cli/src/cmds/stats/stats.ts): simplify appmap file resolution logic
test(cli/tests/unit/stats/stats.spec.ts): adjust and add tests for appmap file resolution

2023-09-11 01:50 UTC, dustinbyrne requested changes
Thanks @moxw! The change looks great.

We use [`semantic-release`](https://semantic-release.gitbook.io/semantic-release/) to automatically version, update CHANGELOG entries and release the packages in this repo. Only `fix` or `feat` commits will trigger that to happen. Do you mind rebasing this to mark this change as a `fix`? No need to include a scope.

Otherwise, the code looks great. We can merge this after the rebase. :+1:

2023-09-11 22:15 UTC, moxw commented
> Thanks @moxw! The change looks great.
> 
> We use [`semantic-release`](https://semantic-release.gitbook.io/semantic-release/) to automatically version, update CHANGELOG entries and release the packages in this repo. Only `fix` or `feat` commits will trigger that to happen. Do you mind rebasing this to mark this change as a `fix`? No need to include a scope. If you're interested in reading more, we follow the conventional commits specification outlined here: https://conventionalcommits.org
> 
> Otherwise, the code looks great. We can merge this after the rebase. 👍

Done, let me know if this is good.

2023-09-12 19:08 UTC, dustinbyrne approved these changes
Perfect! Thank you.

2023-09-12 19:09 UTC, merged

2023-09-12 21:54 UTC, appland-release commented
:tada: This PR is included in version @appland/appmap-v3.96.1 :tada:

The release is available on:
- `@appland/appmap-v3.96.1`
- `@appland/appmap-v3.96.1`
- [GitHub release](https://github.com/getappmap/appmap-js/releases/tag/%40appland/appmap-v3.96.1)
- `@appland/appmap-v3.96.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: