Long function call labels on top of lifelines
getappmap/appmap-js pull request #1367
Opened 2023-09-09 20:42 UTC by moxw

Fixes: #1051 
style(CallAction.vue): add position:relative to .connecting-span for better alignment
test(sequenceDiagram.spec.js): verify .call-line-segment.connecting-span has position relative

2023-09-12 19:07 UTC, dustinbyrne requested changes
Thanks for this. Do you mind adding a transparent background to the labels? I think it helps clear up any confusion about which element is in front of the other. E.g., here's a `background-color` of `rgba(0,0,0,.7)` on [`.label .name`](https://github.com/getappmap/appmap-js/blob/main/packages/components/src/components/sequence/CallLabel.vue#L169)
![image](https://github.com/getappmap/appmap-js/assets/8737782/1ff02819-2d97-4c81-bb8a-7cbab7426f2f)

It's just a small change I'd usually just add it myself but I can't push to your fork :smile:

2023-09-12 19:17 UTC, moxw commented
> Thanks for this. Do you mind adding a transparent background to the labels? I think it helps clear up any confusion about which element is in front of the other. E.g., here's a `background-color` of `rgba(0,0,0,.7)` on [`.label .name`](https://github.com/getappmap/appmap-js/blob/main/packages/components/src/components/sequence/CallLabel.vue#L169) ![image](https://user-images.githubusercontent.com/8737782/267434344-1ff02819-2d97-4c81-bb8a-7cbab7426f2f.png)
> 
> It's just a small change I'd usually just add it myself but I can't push to your fork 😄

Done, added.

2023-09-13 14:20 UTC, dustinbyrne approved these changes
Perfect, thank you!

2023-09-13 14:21 UTC, merged

2023-09-13 15:13 UTC, appland-release commented
:tada: This PR is included in version @appland/components-v2.62.0 :tada:

The release is available on:
- `@appland/components-v2.62.0`
- `@appland/components-v2.62.0`
- [GitHub release](https://github.com/getappmap/appmap-js/releases/tag/%40appland/components-v2.62.0)
- `@appland/components-v2.62.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: