feat: Expand inventory and run stats
getappmap/appmap-js pull request #1456
Opened 2023-11-03 19:49 UTC by kgilpin

## Configuration report

Configuration  report is expanded to provide:

* largeAppMaps
* frequentFunctions

To help the user streamline and prune their config.

**Example**

https://gist.github.com/kgilpin/1bd0783c330743ae2440522ce0f00e97

```json
"largeAppMaps": {
    "tmp/appmap/minitest/Password_resets_password_resets.appmap.json": 2150673,
    "tmp/appmap/minitest/Microposts_interface_micropost_interface.appmap.json": 2039187,
    "tmp/appmap/minitest/Users_login_login_with_valid_information_followed_by_logout.appmap.json": 982768
}
```

```json
"frequentFunctions": {
    "function:ruby/Array#pack": {
      "function": "function:ruby/Array#pack",
      "count": 3410,
      "size": 1428513,
      "location": "<internal:pack>:133"
    },
    "function:logger/Logger::LogDevice#write": {
      "function": "function:logger/Logger::LogDevice#write",
      "count": 1200,
      "size": 620728,
      "location": "/Users/kgilpin/.rbenv/versions/3.0.2/lib/ruby/3.0.0/logger/log_device.rb:31"
    }
}
```

## Project summary report

Project summary report shows number of rule matches rather than number of distinct findings.

**Example**

https://gist.github.com/kgilpin/5b455bdde3c5e0f7ad396a6585b46391

```md
### Overview of problems and flaws

AppMap detected 4 types of problems and flaws in the runtime code review of your project. 
Here's a list of the types of problems that have been found:

| Rule | Impact Domain |
| --- | --- |
| [exec-of-untrusted-command](https://appmap.io/docs/reference/rules/exec-of-untrusted-command) | Security |
| [n-plus-one-query](https://appmap.io/docs/reference/rules/n-plus-one-query) | Performance |
| [secret-in-log](https://appmap.io/docs/reference/rules/secret-in-log) | Security |
| [update-in-get-request](https://appmap.io/docs/reference/rules/update-in-get-request) | Maintainability |
```

2023-11-03 21:18 UTC, brikelly requested changes
Found a few things to change in the strings/copy

2023-11-03 21:18 UTC, brikelly commented on packages/cli/resources/inventory-report/welcome/welcome.hbs
> +Some tests can produce large AppMaps, because those they exercise longer or highly repeated code paths.
```suggestion
Some tests can produce large AppMaps, because they exercise longer or highly repeated code paths. 
```

2023-11-03 21:18 UTC, brikelly commented on packages/cli/resources/inventory-report/welcome/welcome.hbs
> +are less than 10 MB in size. You may want to consider disabling AppMap for tests that produce really
```suggestion
are less than 10 MB in size. You may want to consider disabling AppMap for tests that produce
```

2023-11-03 21:18 UTC, brikelly commented on packages/cli/resources/inventory-report/welcome/welcome.hbs
> +large AppMaps, since they can slow down your CI job and they are hard to analyze. Also, note that
Saying that they're "hard to analyze" makes it sound like our product isn't very capable. Is there some other reason, preferably more specific, that we could use here?

2023-11-03 21:18 UTC, brikelly commented on packages/cli/resources/inventory-report/welcome/welcome.hbs
> +the AppMap agent. For example, the AppMap agent automatically functions that are
```suggestion
the AppMap agent. For example, the AppMap agent automatically records functions that are
```

2023-11-03 21:18 UTC, brikelly commented on packages/cli/resources/inventory-report/welcome/welcome.hbs
> +You can disable recording of a class or functions by updating the _appmap.yml_ configuration file.
```suggestion
You can disable recording of a class or function by updating the _appmap.yml_ configuration file.
```

2023-11-03 21:33 UTC, dustinbyrne approved these changes
This change looks good on my end.

2023-11-04 14:27 UTC, merged

2023-11-04 14:58 UTC, appland-release commented
:tada: This PR is included in version @appland/client-v1.8.1 :tada:

The release is available on:
- `@appland/client-v1.8.1`
- `@appland/client-v1.8.1`
- [GitHub release](https://github.com/getappmap/appmap-js/releases/tag/%40appland/client-v1.8.1)
- `@appland/client-v1.8.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-11-04 15:07 UTC, appland-release commented
:tada: This PR is included in version @appland/appmap-v3.107.0 :tada:

The release is available on:
- `@appland/appmap-v3.107.0`
- `@appland/appmap-v3.107.0`
- [GitHub release](https://github.com/getappmap/appmap-js/releases/tag/%40appland/appmap-v3.107.0)
- `@appland/appmap-v3.107.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: