Collapsible sidebar
getappmap/appmap-js pull request #1495
Opened 2023-12-13 21:36 UTC by ahtrotta

2023-12-14 12:31 UTC, kgilpin commented
Thanks for getting this going @ahtrotta   

So I guess now when the horizontal space gets low, the LHS panel will collapse rather than disappear completely?

2023-12-14 14:21 UTC, ahtrotta commented
> Thanks for getting this going @ahtrotta
> 
> So I guess now when the horizontal space gets low, the LHS panel will collapse rather than disappear completely?

Yeah, exactly. When the width is less than 900px the LHS panel will be collapsed by default. Of course, we can change the threshold quite easily if we want.

2023-12-14 19:03 UTC, dustinbyrne requested changes
This looks great! The issue with 'Clear' described below is really the only blocker.

2023-12-14 19:03 UTC, dustinbyrne commented on packages/components/src/pages/VsCodeExtension.vue
> +      this.autoResizeLeftPanel();
We should also add a test for this

2023-12-14 20:57 UTC, ahtrotta commented on packages/components/src/pages/VsCodeExtension.vue
> +      this.autoResizeLeftPanel();
Good catch, thanks! I fixed this and added a test.

2023-12-14 20:59 UTC, ahtrotta commented on packages/components/src/pages/VsCodeExtension.vue
> +      </div>
As mentioned at the demo session, I'm going to potentially change how this works by making the side panel slide out over the map. If we go in that direction then these animations are moot, so I'd like to see what happens on that front before investing time into tweaking this version of the feature.

2023-12-14 21:00 UTC, ahtrotta commented on packages/components/src/pages/VsCodeExtension.vue
>        }
Yeah, good suggestion. I made it so that if the screen is less than `600px` wide then the sidebar menu is fullscreen.

2023-12-19 15:45 UTC, dustinbyrne approved these changes

2023-12-19 15:48 UTC, merged

2023-12-19 16:23 UTC, appland-release commented
:tada: This PR is included in version @appland/components-v3.17.0 :tada:

The release is available on:
- `@appland/components-v3.17.0`
- `@appland/components-v3.17.0`
- [GitHub release](https://github.com/getappmap/appmap-js/releases/tag/%40appland/components-v3.17.0)
- `@appland/components-v3.17.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: