Fix the clipping of long hover labels in sequence diagram
getappmap/appmap-js pull request #1539
Opened 2024-01-16 22:15 UTC by ahtrotta

Fixes #1424

2024-01-22 18:29 UTC, dustinbyrne requested changes
This change affects the placement of the elapsed time spans. They're now underneath long labels.
![image](https://github.com/getappmap/appmap-js/assets/8737782/e5ee3038-aa48-40b9-a8d1-342aaac00649)
 
Also, it looks like return values are no longer truncated.
Before
![image](https://github.com/getappmap/appmap-js/assets/8737782/be64a28a-dcf8-4e69-bfb1-0594618239ba)
After
![image](https://github.com/getappmap/appmap-js/assets/8737782/2e3dc53c-a576-4f06-981c-18b1f882e58b)

2024-01-22 20:38 UTC, ahtrotta commented
> This change affects the placement of the elapsed time spans. They're now underneath long labels. ![image](https://private-user-images.githubusercontent.com/8737782/298684380-e5ee3038-aa48-40b9-a8d1-342aaac00649.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NTQ3MjIsIm5iZiI6MTcwNTk1NDQyMiwicGF0aCI6Ii84NzM3NzgyLzI5ODY4NDM4MC1lNWVlMzAzOC1hYTQ4LTQwYjktYThkMS0zNDJhYWFjMDA2NDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMjAxMzQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTY1YTI2Zjg1M2VlYzhjZDg5NTYxZmQ3N2Q4NGVjZjZjNWZiMjIwYjNiNmQzMTc1ZTYyYWVlZmUwMjgyNmIwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aEXJntA5M0FkxmNj2KdKRANXnH4nzYOFvFQj3GhzRJ4)
> 
> Also, it looks like return values are no longer truncated. Before ![image](https://private-user-images.githubusercontent.com/8737782/298685105-be64a28a-dcf8-4e69-bfb1-0594618239ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NTQ3MjIsIm5iZiI6MTcwNTk1NDQyMiwicGF0aCI6Ii84NzM3NzgyLzI5ODY4NTEwNS1iZTY0YTI4YS1kY2Y4LTRlNjktYmZiMS0wNTk0NjE4MjM5YmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMjAxMzQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTM2ZmEwMjE4ZWZlODMzMWY5OGNmNjVmMjhkMjQwZGZmNjU5YzZmN2EwYmFiNzdhMTdjMWRkNmM0NzdiM2QwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CY0HkJA7Y4fVjcvDVtmiPQrpBqwV1CSDJ6yUYWHAU2g) After ![image](https://private-user-images.githubusercontent.com/8737782/298685158-2e3dc53c-a576-4f06-981c-18b1f882e58b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NTQ3MjIsIm5iZiI6MTcwNTk1NDQyMiwicGF0aCI6Ii84NzM3NzgyLzI5ODY4NTE1OC0yZTNkYzUzYy1hNTc2LTRmMDYtOTgxYy0xOGIxZjg4MmU1OGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMjAxMzQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTExZWExMzQwODg1NjVkOWM0MGMyNjUwM2JkYWEyY2MwZGQ3MGI0MDg1NzdjOTZjODE5YjMxNGQ2NDYxMTExYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hcl7-VneDcgu787cKnXVen1d5VY6vKEBb3_SjU2EWbw)

Thanks Dustin, I fixed these problems. It looks like Chromatic stopped working, though.

2024-01-23 19:45 UTC, dustinbyrne approved these changes

2024-01-23 19:46 UTC, dustinbyrne commented
Looks good. There's a `fixup` commit in the history, so I'll let you merge.

2024-01-23 20:06 UTC, merged