feat: AppMap stats in the Navie view are reactive
getappmap/appmap-js pull request #1613
Opened 2024-03-01 21:25 UTC by dustinbyrne

Changes to 'most recent AppMaps' will trigger a reload of AppMap stats. The RPC call is debounced to one request per second.

[Peek 2024-03-01 16-22.webm](https://github.com/getappmap/appmap-js/assets/8737782/d09ebcac-f6f2-4f63-823e-67838fa8290e)

Resolves #1607

2024-03-04 20:54 UTC, ahtrotta approved these changes

2024-03-04 22:55 UTC, kgilpin requested changes

2024-03-04 22:55 UTC, kgilpin commented on packages/components/src/pages/ChatSearch.vue
> +      }, 1000),
The AppMap stats can be expensive to compute. I'd suggest a longer delay, maybe 5 seconds. Or, it should be adaptive to however long the stats took to compute the last time. Requesting stats every 1 second could be punishing for large projects.

2024-03-14 19:09 UTC, ahtrotta commented
I think it might be good if we get this merged before we ship the [new status bar in the chat](https://github.com/getappmap/appmap-js/pull/1627). Otherwise users might be stuck with a big red status bar even if they have AppMaps.

2024-03-14 20:26 UTC, kgilpin commented
> I think it might be good if we get this merged before we ship the [new status bar in the chat](https://github.com/getappmap/appmap-js/pull/1627). Otherwise users might be stuck with a big red status bar even if they have AppMaps.

The behavior of this PR is intended to be (must be) backwards compatible. Because we have no way of forcing users to upgrade.

2024-03-15 20:48 UTC, merged

2024-03-15 21:15 UTC, appland-release commented
:tada: This PR is included in version @appland/components-v4.8.0 :tada:

The release is available on:
- `@appland/components-v4.8.0`
- `@appland/components-v4.8.0`
- [GitHub release](https://github.com/getappmap/appmap-js/releases/tag/%40appland/components-v4.8.0)
- `@appland/components-v4.8.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: