Update @appland/navie to include code editor
getappmap/appmap-js pull request #1707
Opened 2024-04-05 21:10 UTC by ahtrotta

This is part of [this PR](https://github.com/getappmap/appmap-js/pull/1706), but I want to release a new version of `@appland/navie` first, so that `@appland/cli` can bump it's dependencies using the new `navie` version.

2024-04-05 21:47 UTC, dustinbyrne requested changes
I think it's worth sorting out the duplicate array. Also, it'd be worth adding a test.

2024-04-05 21:58 UTC, kgilpin commented on packages/navie/src/services/project-info-service.ts
> +      ],
Yeah, if it's not there just ignore this section. The user may be using an outdated client, or somehow calling Navie from a different environment (custom plugin for neovim? :-))

Unlike with missing project info, it's not something we need to try and direct the AI to take action on.

2024-04-05 21:59 UTC, kgilpin commented on packages/navie/src/services/project-info-service.ts
>          return value;
Also we want that to be like `codeEditorName` rather than just `name`

2024-04-05 22:00 UTC, kgilpin commented
> I think it's worth sorting out the duplicate array. Also, it'd be worth adding a test.

Tests of the prompt behavior would be really useful, and handy to place in the PR description because anything that affects the prompt is super important.

2024-04-29 15:27 UTC, ahtrotta commented
No longer relevant

2024-04-29 15:27 UTC, closed without merging