feat: Update Java, Ruby and Python recording instructions
getappmap/appmap-js pull request #1871
Opened 2024-07-05 18:44 UTC by dustinbyrne

This brings them in line with the (already released and live in VS Code) JavaScript instructions.

Python is also updated to include changes introduced in v2 of the agent, such as running `appmap-python`. This will need some fact checking.

2024-07-05 20:46 UTC, apotterri commented
Would it be possible to attach some snapshots of the updated instructions for Java and Python? I'll be happy to review them, but it's really hard to sift through all the markup surrounding them in the commits.

2024-07-08 13:11 UTC, dustinbyrne commented
Are you able to access this page?
https://5fe18baf66f2280021e634d0-jvvulqxbcs.chromatic.com/?path=/story/pages-vs-code-install-guide-pages-record-appmaps--python-only

2024-07-08 13:15 UTC, apotterri commented
Yup, I'll review from there.

2024-07-08 13:26 UTC, apotterri requested changes
Needs a tweak for flask, but looks good otherwise.

2024-07-08 13:26 UTC, apotterri commented on packages/components/src/components/install-guide/record-instructions/Python.vue
> +      'flask --app main.app',
This should be `flask --debug --app main.app`.

2024-07-08 13:26 UTC, apotterri commented on packages/components/src/components/install-guide/record-instructions/Python.vue
> +      'flask --app main.app',
Also, in the chromatic page at least, these scroll by really quickly.

2024-07-12 17:06 UTC, merged

2024-07-12 17:29 UTC, appland-release commented
:tada: This PR is included in version @appland/components-v4.28.0 :tada:

The release is available on:
- `@appland/components-v4.28.0`
- [GitHub release](https://github.com/getappmap/appmap-js/releases/tag/%40appland/components-v4.28.0)
- `@appland/components-v4.28.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: