`scan --watch` works correctly even when the appmap dir doesn't initially exist
getappmap/appmap-js pull request #756
Opened 2022-10-04 11:54 UTC by dividedmind

Also, fix paths handling for windows.

Fixes #753 .

2022-10-06 17:29 UTC, ahtrotta commented
It looks like most of the tests didn't run in the [Windows Travis build](https://app.travis-ci.com/github/getappmap/appmap-js/jobs/584668737), so I ran them on my local Windows machine and got these test failures:

![image](https://user-images.githubusercontent.com/45714532/194378483-87dd4959-c381-4779-968e-95bd8cab7d64.png)

2022-10-06 18:15 UTC, ahtrotta commented on packages/scanner/src/cli/scan/watchScan.ts
> +      path.basename(filePath) === 'mtime' && this.enqueue(filePath);
Does this function need to be bound to `this` so that it has the right execution context when passed as an argument below?

2022-10-06 19:17 UTC, ahtrotta requested changes
Looks good overall. Just need to fix the Windows test failures and revert to using `sinon`

2022-10-06 22:30 UTC, ahtrotta commented
I've looked into the Windows test failures and the problem is the custom `ignored` function. If I switch it to use the `['**/node_modules/**', '**/.git/**']` glob pattern, then it works.

2022-10-07 01:01 UTC, dividedmind commented
> I've looked into the Windows test failures and the problem is the custom `ignored` function. If I switch it to use the `['**/node_modules/**', '**/.git/**']` glob pattern, then it works.

The `ignored` function is kinda crucial for cutting down the search tree and limiting the search to the appmap dir. I'll try to figure out where it's having issues.

2022-10-07 02:02 UTC, dividedmind commented
> Also, based on the conversation in standup today and from [this PR](https://github.com/getappmap/appmap-js/pull/762), it seems like the consensus is to keep using `sinon` instead of `jest` mocks.

I wouldn't call it a consensus per se, just that it didn't make sense to convert a bunch of existing tests without previous discussion ;)

2022-10-07 03:22 UTC, dividedmind commented
Thanks for testing with windows! I think the latest change did the trick. Fingers crossed.

2022-10-07 15:52 UTC, ahtrotta commented
It looks like most of the tests are working now :)

I'm still getting a failure on this one, though:

![image](https://user-images.githubusercontent.com/45714532/194595914-aef4884c-91a5-402e-8096-a21e3cb8dafb.png)

2022-10-10 13:01 UTC, dividedmind commented
> It looks like most of the tests are working now :)
> 
> I'm still getting a failure on this one, though:
> 
> ![image](https://user-images.githubusercontent.com/45714532/194595914-aef4884c-91a5-402e-8096-a21e3cb8dafb.png)

This one looks unrelated to the pull request substance, it's just Windows being Windows and breaking on temp directory cleanup. I think it's safe to leave it as it is until we circle back to take the time to fix tests on Windows more broadly. WDYT?

2022-10-10 13:23 UTC, ahtrotta approved these changes
I agree, and I'm going start looking into Windows test failures soon.

2022-10-10 13:52 UTC, dividedmind commented
> I agree, and I'm going start looking into Windows test failures soon.

Thanks! I created an issue for this: #771

2022-10-11 13:21 UTC, merged