fix: Fix TypeError: Cannot read properties of undefined
getappmap/appmap-js pull request #772
Opened 2022-10-10 17:00 UTC by symwell

If validateProject fails to `JSON.parse(stdout)`, print out the stdout that failed to be parsed and display an error message.

Fixes https://github.com/getappmap/appmap-js/issues/770

2022-10-12 16:51 UTC, dividedmind requested changes
Looks ok, but could you please add a test case for this? Thanks.

2022-10-12 16:53 UTC, symwell commented
I tested it like this https://github.com/getappmap/appmap-js/issues/770#issuecomment-1273587287.

Will try to add a testcase.

2022-10-12 18:11 UTC, dividedmind commented
> I tested it like this [#770 (comment)](https://github.com/getappmap/appmap-js/issues/770#issuecomment-1273587287).
> 
> Will try to add a testcase.

Yeah, I've seen, but it'd be nice to have an automated test so there's no regression.

2022-10-12 18:12 UTC, symwell commented
Added a testcase.  Waiting for the build.

2022-10-13 16:38 UTC, symwell commented
Fixed.

2022-10-14 15:55 UTC, symwell commented
I think the error is simply that `error` isn't an array.  There's no `error` in the validationResult.
```
validationResult is 
{
  filename: 'appmap.yml',
  configuration: { contents: 'name: js-project\npackages: []\n' }
}
```

I plan to create a new pr that checks if `error` exists.

2022-10-14 16:25 UTC, symwell commented
Simpler fix https://github.com/getappmap/appmap-js/pull/787

2022-10-17 13:20 UTC, symwell commented
Closing, since we now believe the real fix was https://github.com/getappmap/appmap-js/pull/787

2022-10-17 13:20 UTC, closed without merging