fix: Prevent EPERM/EACCES errors while watching AppMaps if a directory cannot be read
getappmap/appmap-js pull request #883
Opened 2022-12-02 21:45 UTC by dustinbyrne

If the user does not have permissions to read a directory under `--appmap-dir`, an `EPERM`/`EACCES` error would panic the process (even in `--watch` mode).

Instead, these errors will be ignored and we'll continue scanning what we can.

I wasn't sure of an easy way to test an `EPERM` without involving other OS users, so I've omitted the test for now. Behavior should otherwise be the same.

Resolves #880

2022-12-06 15:33 UTC, apotterri requested changes
I think this really needs to include a test.

2022-12-06 15:33 UTC, apotterri commented on packages/cli/src/fingerprint/globber.ts
> +      strict: false,
`strict` defaults to `false`, so this has no effect.

2022-12-06 17:23 UTC, dustinbyrne commented
I've added a test which fails prior to this fix. Turns out it was more simple than expected :+1:

2022-12-06 17:40 UTC, apotterri commented on packages/cli/src/fingerprint/globber.ts
> +      strict: false,
Sorry about that, looks like their doc needs an update: https://github.com/isaacs/node-glob#options .

2022-12-06 17:42 UTC, apotterri approved these changes
Thanks for the test, looks good.

2022-12-06 17:56 UTC, apotterri commented
Build's red, though,

2022-12-07 15:03 UTC, merged

2022-12-07 15:48 UTC, appland-release commented
:tada: This PR is included in version @appland/appmap-v3.52.2 :tada:

The release is available on:
- `@appland/appmap-v3.52.2`
- [GitHub release](https://github.com/getappmap/appmap-js/releases/tag/%40appland/appmap-v3.52.2)
- `@appland/appmap-v3.52.2`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: